export const AlumniMembers = [
  {
    name: "Navpreet Kaur",
    position: "Full Stack Cloud Application Developer at IBM",
    mailId: "nkaur051@uottawa.ca",
    imagePath: "/assets/navpreet.jpg",
    linkedinId: "https://www.linkedin.com/in/navpreet-kaur-uottawa/",
  },
  {
    name: "Ajay Modagi",
    position: "Dissemination Officer at Statistics Canada",
    mailId: "amoda040@uottawa.ca",
    imagePath: "/assets/ajay.jpg",
    linkedinId: "https://www.linkedin.com/in/amodagi",
  },
  {
    name: "Akashdeep Singh",
    position: "Graduated from University of Ottawa",
    mailId: "asing255@uottawa.ca",
    imagePath: "/assets/akashdeep.jpg",
    linkedinId: "https://www.linkedin.com/in/akashdeep-singh1997",
  },
  {
    name: "Mohammed Fahim",
    position: "Electrical Engineer at IntellectuLogy Solutions Inc.",
    mailId: "mfahi009@uottawa.ca",
    imagePath: "/assets/fahim.png",
    linkedinId: "https://www.linkedin.com/in/mohammadfaheem/",
  },
  {
    name: "Roopleen Kaur",
    position: "Data Analyst at AedoAI Inc",
    mailId: "rkaur050@uottawa.ca",
    imagePath: "/assets/roopleen.jpeg",
    linkedinId: "https://www.linkedin.com/in/roopleen-kaur/",
  },
  {
    name: "Abdullah-Al-Mehedi Hassan",
    position: "Research Analyst at Ontario Treasury Board Secretariat",
    mailId: "ahasa085@uottawa.ca",
    imagePath: "/assets/abdullah.jpg",
    linkedinId: "https://www.linkedin.com/in/a-a-m-h/",
  },
  {
    name: "Shubhneet Baath",
    position: "Developer at AedoAI Inc.",
    mailId: "sbaat080@uottawa.ca",
    imagePath: "/assets/shubhneet.jpeg",
    linkedinId: "https://www.linkedin.com/in/shubhneetbaath/",
  },
  {
    name: "Mansher Sidhu",
    position: "Assistant, Operations & Training at uOttawa",
    mailId: "msidh098@uottawa.ca",
    imagePath: "/assets/mansher.jpg",
    linkedinId: "https://www.linkedin.com/in/mansher-singh-sidhu-140a15122/",
  },
  {
    name: "Muhammad Atif",
    position: "Data Analyst (Burning Glass Technologies)",
    mailId: "matif062@uottawa.ca",
    imagePath: "/assets/akashdeep.jpg",
    linkedinId: "https://www.linkedin.com/in/muhammad-atif-046b96127/",
  },
  {
    name: "Akansha Agnihotri",
    position: "Project Manager & Front End Developer at ShakaCode",
    mailId: "aagni073@uottawa.ca",
    imagePath: "/assets/akansha.jpg",
    linkedinId: "https://www.linkedin.com/in/agnihotriakansha/",
  },
];
